asr_model: openai/whisper-large-v3-turbo
llm_model: gemini-2.5-flash
svs_model: espnet/aceopencpop_svs_visinger2_40singer_pretrain
melody_source: sample-lyric-kising
language: mandarin
prompt_template_character: Limei
speaker: 5
cache_dir: .cache

track_latency: True
evaluators:
  svs:
    - singmos
    - per
    - melody
    - aesthetic
