asr_model: openai/whisper-medium
llm_model: meta-llama/Llama-3.1-8B-Instruct
svs_model: espnet/visinger2-zh-jp-multisinger-svs
melody_source: sample-lyric-kising
language: mandarin
prompt_template_character: Yaoyin
speaker: resources/singer/singer_embedding_ace-2.npy
cache_dir: .cache

track_latency: True
